# backend/app/core/constants.py
# 1. 부위별 상세 운동 카테고리 정의
EXERCISE_CATEGORIES = {
    "가슴": ["벤치프레스", "인클라인 벤치프레스", "머신플라이"],
    "등": ["바벨 로우", "데드리프트", "랫풀다운"],
    "하체": ["스쿼트", "런지", "스모 데드리프트"],
    "어깨": ["오버헤드 프레스", "사이드 레터럴 레이즈", "프론트 레이즈"],
    "복근": ["플랭크", "크런치", "레그 레이즈"],
    "팔": ["바벨 컬", "클로즈 그립 벤치프레스", "라잉 트라이셉스 익스텐션"],
}
# 2. 운동별 카메라 가이드
CAMERA_GUIDE = {
    "벤치프레스": "정면에서 촬영하세요. 카메라를 발 아래쪽에 두고 바가 정면으로 보이도록 배치하면 그립 너비와 허리 아치를 판정하기 좋습니다.",
    "스쿼트": "측면에서 촬영하세요. 무릎·허리 라인이 한눈에 보이게 옆에서 찍어야 무릎 안쪽 꺾임과 척추 각도를 판정할 수 있습니다.",
    "데드리프트": "측면에서 촬영하세요. 바·허리·무릎이 한 라인에 들어오도록 옆면을 잡으면 척추 중립 여부를 판정하기 좋습니다.",
    "바벨 컬": "측면에서 촬영하세요. 한쪽 팔(어깨·팔꿈치·손목)과 골반이 한 화면에 들어와야 상체 반동과 팔꿈치 흔들림을 판정할 수 있습니다.",
    "플랭크": "측면에서 촬영하세요. 머리부터 발끝까지 일직선이 한 화면에 들어와야 엉덩이 높낮이를 판정할 수 있습니다.",
    "런지": "측면에서 촬영하세요. 앞다리 무릎 각도와 발끝 위치가 보여야 무릎이 발끝을 넘는지를 판정할 수 있습니다.",
    "오버헤드 프레스": "정면에서 촬영하세요. 양 어깨·팔꿈치·손목이 한 화면에 들어와야 좌우 균형과 락아웃 정도를 판정할 수 있습니다.",
    "바벨 로우": "측면에서 촬영하세요. 어깨·골반·무릎·팔꿈치가 한 라인에 보여야 척추 중립과 힙 힌지 각도를 판정할 수 있습니다.",
    "인클라인 벤치프레스": "정면에서 촬영하세요. 인클라인 각도(30~45°) 기준 발 아래쪽에서 바가 정면으로 보이게 배치하면 그립 너비와 좌우 밸런스를 판정할 수 있습니다.",
    "랫풀다운": "정면에서 촬영하세요. 머리부터 골반까지 상체와 양팔이 한 화면에 들어와야 그립 너비, 상체 기울기, 좌우 균형을 판정할 수 있습니다.",
    "사이드 레터럴 레이즈": "정면에서 촬영하세요. 양팔이 측면으로 어깨 라인까지 올라가는 모습이 화면에 들어와야 가동범위와 좌우 비대칭을 판정할 수 있습니다.",
    "머신플라이": "정면에서 촬영하세요. 양 어깨와 양 손목이 한 화면에 들어와야 가동범위, 좌우 비대칭, 상체 흔들림을 판정할 수 있습니다.",
    "스모 데드리프트": "측면에서 촬영하세요. 어깨·골반·무릎이 한 라인에 보여야 척추 중립, 락아웃, 바 경로를 판정할 수 있습니다.",
    "프론트 레이즈": "측면에서 촬영하세요. 어깨·팔꿈치·손목과 골반이 한 화면에 들어와야 정점 높이, 상체 젖힘, 반동을 판정할 수 있습니다.",
    "클로즈 그립 벤치프레스": "정면에서 촬영하세요. 양 어깨·팔꿈치·손목이 한 화면에 들어와야 그립 너비, 팔꿈치 벌어짐, 좌우 균형을 판정할 수 있습니다.",
    "라잉 트라이셉스 익스텐션": "측면에서 촬영하세요. 누운 자세에서 한쪽 어깨·팔꿈치·손목이 보여야 상완 흔들림과 가동범위를 판정할 수 있습니다.",
    "크런치": "측면에서 촬영하세요. 어깨·골반·무릎이 한 화면에 들어와야 상체 들어올림 정도와 허리 부착 여부를 판정할 수 있습니다.",
    "레그 레이즈": "측면에서 촬영하세요. 골반·무릎·발목이 한 화면에 들어와야 다리 각도, 허리 부착, 무릎 굽힘 정도를 판정할 수 있습니다.",
}
# 3. 기존의 상세한 피드백 메시지
FEEDBACK_MESSAGES = {
    "excessive_arch": "허리가 과도한 아치 자세입니다. 허리를 너무 아치 모양으로 만들지 말고 가슴을 피려고 노력하세요. 골반을 조금 더 들어올리고 복부를 긴장시켜 허리를 평평하게 유지하세요.",
    "arms_spread": "바를 너무 넓게 잡은 자세입니다. 어깨 너비보다 약간만 넓게 잡는 것이 좋습니다.",
    "arms_narrow": "바를 너무 좁게 잡은 자세입니다. 어깨 너비보다 조금 넓게 잡는 것이 좋습니다.",
    "spine_neutral": "척추가 중립이 아닌 자세입니다. 척추가 과도하게 굽지 않도록 가슴을 들어올리고 어깨를 뒤로 넣으세요.",
    "caved_in_knees": "무릎이 움푹 들어간 자세입니다. 엉덩이를 뒤로 빼서 무릎과 발끝을 일직선으로 유지하세요.",
    "feet_spread": "발을 너무 넓게 벌린 자세입니다. 발을 어깨 너비 정도로만 벌리도록 좁히세요.",
    "lean_back": "상체를 너무 뒤로 젖혔습니다. 반동을 쓰지 말고 코어를 잡은 채로 상체를 세워 컬을 수행하세요.",
    "loose_upper_arm": "팔꿈치가 흔들립니다. 상완(어깨~팔꿈치)을 몸통 옆에 고정한 상태로 들어올리세요.",
    "weak_peak_contraction": "끝까지 짜내지 못했습니다. 정점에서 이두를 한 박자 더 강하게 수축시키세요.",
    "plank_high_back": "엉덩이가 너무 높습니다. 골반을 낮춰 머리부터 발끝까지 일직선을 만드세요.",
    "plank_low_back": "허리가 처졌습니다. 코어로 골반을 살짝 들어올려 일직선을 유지하세요.",
    "knee_over_toe": "무릎이 발끝보다 앞으로 나왔습니다. 엉덩이를 뒤로 빼고 정강이를 수직에 가깝게 두세요.",
    "ohp_uneven_press": "양쪽 손목 높이 차이가 큽니다. 좌우 균형을 맞춰 동시에 밀어 올리세요.",
    "ohp_incomplete_lockout": "정점에서 팔을 끝까지 펴지 못했습니다. 머리 위에서 팔꿈치를 완전히 잠그세요.",
    "row_round_back": "등이 굽었습니다. 가슴을 들고 어깨를 뒤로 빼서 척추 중립을 유지하세요.",
    "row_too_upright": "상체를 너무 세웠습니다. 상체를 약 45° 정도 앞으로 숙여 힙 힌지 자세를 유지하세요.",
    "row_body_english": "반동을 너무 사용했습니다. 상체 각도를 고정한 채 팔로만 당기세요.",
    "incline_partial_rom": "바를 가슴까지 충분히 내리지 못했습니다. 가동범위를 끝까지 활용하세요.",
    "incline_uneven_press": "좌우 손목 높이 차이가 큽니다. 양손이 동시에 정점에 닿도록 밀어 올리세요.",
    "lat_excessive_lean": "상체를 너무 뒤로 젖혀서 등 운동이 아닌 로우 동작이 됐습니다. 상체 기울기를 10~15° 정도로만 유지하세요.",
    "lat_partial_rom": "바를 가슴까지 충분히 당기지 못했습니다. 광배근에 자극이 잘 가도록 가슴 윗부분까지 끌어내리세요.",
    "lat_uneven_pull": "양쪽 손목 높이 차이가 큽니다. 좌우 균형을 맞춰 동시에 당기세요.",
    "lat_body_english": "반동을 너무 사용했습니다. 상체 각도를 고정한 채 등 근육으로만 당기세요.",
    "slr_too_high": "팔을 어깨선 위로 너무 들어올렸습니다. 어깨 임핀지먼트 위험이 있으니 수평선 정도까지만 들어올리세요.",
    "slr_partial_rom": "팔을 수평까지 충분히 들어올리지 못했습니다. 어깨 측면이 자극되도록 수평까지 들어올리세요.",
    "slr_uneven": "양팔 높이 차이가 큽니다. 좌우 동시에 같은 높이로 들어올리세요.",
    "slr_body_english": "반동을 너무 사용했습니다. 상체를 고정한 채 어깨 측면 근육으로만 들어올리세요.",
    "fly_too_open": "팔을 너무 뒤로 펼쳤습니다. 어깨 후방 부상 위험이 있으니 어깨 라인 정도까지만 펼치세요.",
    "fly_partial_rom": "양손이 가슴 앞 가운데까지 충분히 모이지 않았습니다. 정점에서 가슴을 짜내듯 양손을 모으세요.",
    "fly_uneven": "좌우 손목 높이 차이가 큽니다. 양손이 동시에 같은 높이로 움직이도록 균형을 맞추세요.",
    "fly_body_english": "상체를 너무 흔들었습니다. 등을 시트에 붙이고 가슴 근육만으로 모으세요.",
    "sumo_round_back": "등이 굽었습니다. 가슴을 들고 시선을 정면에 두어 척추 중립을 유지하세요.",
    "sumo_partial_lockout": "정점에서 완전히 일어서지 못했습니다. 골반을 앞으로 밀어 상체를 수직으로 세워 락아웃하세요.",
    "sumo_bar_drift": "바가 몸에서 떨어졌습니다. 정강이·허벅지에 바를 붙인 채 직선 경로로 들어올리세요.",
    "sumo_hips_first": "엉덩이가 어깨보다 먼저 올라갔습니다(굿모닝 형태). 가슴을 든 채 어깨와 엉덩이가 같은 비율로 함께 올라오게 하세요.",
    "fr_too_high": "팔을 어깨선 위로 너무 들어올렸습니다. 어깨 임핀지먼트 위험이 있으니 어깨 라인 정도까지만 들어올리세요.",
    "fr_partial_rom": "팔을 어깨 높이까지 충분히 들어올리지 못했습니다. 정점에서 손목이 어깨 높이에 오도록 들어올리세요.",
    "fr_lean_back": "상체를 너무 뒤로 젖혔습니다. 코어를 잡고 상체를 수직으로 유지한 채 팔만 들어올리세요.",
    "fr_body_english": "반동을 너무 사용했습니다. 상체를 고정한 채 어깨 전면 근육으로만 들어올리세요.",
    "cgbp_grip_too_wide": "클로즈그립인데 너무 넓게 잡았습니다. 어깨 너비 또는 약간 좁게 잡아 삼두 자극을 살리세요.",
    "cgbp_partial_rom": "바를 가슴까지 충분히 내리지 못했습니다. 가동범위를 끝까지 활용하세요.",
    "cgbp_uneven_press": "좌우 손목 높이 차이가 큽니다. 양손이 동시에 정점에 닿도록 균형을 맞추세요.",
    "cgbp_elbow_flare": "팔꿈치가 옆으로 너무 벌어졌습니다. 팔꿈치를 몸통에 가깝게 붙여 삼두에 집중하세요.",
    "sc_upper_arm_drift": "상완이 흔들렸습니다. 어깨·팔꿈치 위치를 고정한 채 팔꿈치만 굽혔다 펴세요.",
    "sc_partial_rom": "바를 이마 근처까지 충분히 내리지 못했습니다. 팔꿈치를 더 깊이 굽혀 삼두를 늘리세요.",
    "sc_incomplete_lockout": "정점에서 팔을 끝까지 펴지 못했습니다. 팔꿈치를 완전히 잠가 삼두를 짜내세요.",
    "crunch_too_high": "상체를 너무 높이 들어올렸습니다. 어깨가 바닥에서 살짝 떨어질 정도로만 윗배에 집중해 들어올리세요.",
    "crunch_partial_rom": "상체를 충분히 들어올리지 못했습니다. 윗배가 수축되도록 어깨를 바닥에서 분명히 떼세요.",
    "crunch_lower_back_lift": "허리가 바닥에서 들렸습니다. 허리를 바닥에 붙인 채 윗배 힘만으로 상체를 들어올리세요.",
    "legraise_lower_back_lift": "허리가 바닥에서 들렸습니다. 디스크 부상 위험이 있으니 허리를 바닥에 단단히 붙이고 다리만 움직이세요.",
    "legraise_partial_rom": "다리를 충분히 높이 들어올리지 못했습니다. 다리가 수직에 가깝게 올 때까지 들어올리세요.",
    "legraise_partial_descent": "다리를 끝까지 내리지 않았습니다. 매 rep마다 다리를 거의 바닥 높이까지 내려야 가동범위가 살아납니다.",
    "legraise_excessive_knee_flex": "무릎을 너무 굽혔습니다. 무릎을 거의 펴거나 살짝만 굽힌 채로 다리를 들어올리세요.",
}

ERROR_KEYS = list(FEEDBACK_MESSAGES.keys())

# 4. 추천 자세 이미지 매핑
GUIDE_IMAGES = {
    "벤치프레스": "bench_guide.jpg",
    "스쿼트": "squat_guide.jpg",
    "데드리프트": "dead_guide.jpg",
}




ERROR_CATEGORY_MAP = {
    "excessive_arch": "Posture",
    "spine_neutral": "Posture",
    "arms_spread": "Movement Quality",
    "arms_narrow": "Movement Quality",
    "caved_in_knees": "Stability",
    "feet_spread": "Stability",
    "lean_back": "Posture",
    "loose_upper_arm": "Stability",
    "weak_peak_contraction": "ROM",
    "plank_high_back": "Posture",
    "plank_low_back": "Posture",
    "knee_over_toe": "Stability",
    "ohp_uneven_press": "Stability",
    "ohp_incomplete_lockout": "ROM",
    "row_round_back": "Posture",
    "row_too_upright": "Posture",
    "row_body_english": "Movement Quality",
    "incline_partial_rom": "ROM",
    "incline_uneven_press": "Stability",
    "lat_excessive_lean": "Posture",
    "lat_partial_rom": "ROM",
    "lat_uneven_pull": "Stability",
    "lat_body_english": "Movement Quality",
    "slr_too_high": "ROM",
    "slr_partial_rom": "ROM",
    "slr_uneven": "Stability",
    "slr_body_english": "Movement Quality",
    "fly_too_open": "ROM",
    "fly_partial_rom": "ROM",
    "fly_uneven": "Stability",
    "fly_body_english": "Movement Quality",
    "sumo_round_back": "Posture",
    "sumo_partial_lockout": "ROM",
    "sumo_bar_drift": "Movement Quality",
    "sumo_hips_first": "Movement Quality",
    "fr_too_high": "ROM",
    "fr_partial_rom": "ROM",
    "fr_lean_back": "Posture",
    "fr_body_english": "Movement Quality",
    "cgbp_grip_too_wide": "Movement Quality",
    "cgbp_partial_rom": "ROM",
    "cgbp_uneven_press": "Stability",
    "cgbp_elbow_flare": "Stability",
    "sc_upper_arm_drift": "Stability",
    "sc_partial_rom": "ROM",
    "sc_incomplete_lockout": "ROM",
    "crunch_too_high": "ROM",
    "crunch_partial_rom": "ROM",
    "crunch_lower_back_lift": "Posture",
    "legraise_lower_back_lift": "Posture",
    "legraise_partial_rom": "ROM",
    "legraise_partial_descent": "ROM",
    "legraise_excessive_knee_flex": "Movement Quality",
}

CATEGORY_ORDER = ["Stability", "ROM", "Movement Quality", "Posture", "Core"]

CATEGORY_LABELS = {
    "Stability": "Stability(안정성)",
    "ROM": "Range of Motion(가동범위)",
    "Movement Quality": "Movement Quality(동작 품질)",
    "Posture": "Posture(자세)",
    "Core": "Bracing & Core(코어 긴장)",
}

CATEGORY_PRAISE = {
    "Stability": "균형감 좋습니다.",
    "ROM": "깊이 충분히 내려갑니다. 좋아요.",
    "Movement Quality": "동작 컨트롤이 매끄럽습니다.",
    "Posture": "척추 중립이 잘 유지됩니다.",
    "Core": "복압 거의 완벽합니다.",
}

OVERLAY_MESSAGES = {
    "excessive_arch": "허리 아치 과도",
    "arms_spread": "그립 너무 넓음",
    "arms_narrow": "그립 너무 좁음",
    "spine_neutral": "척추 비중립",
    "caved_in_knees": "무릎 안쪽 꺾임",
    "feet_spread": "보폭이 너무 넓습니다",
    "lean_back": "상체 뒤로 젖힘",
    "loose_upper_arm": "팔꿈치 흔들림",
    "weak_peak_contraction": "수축 부족",
    "plank_high_back": "엉덩이 너무 높음",
    "plank_low_back": "허리 처짐",
    "knee_over_toe": "무릎이 발끝 초과",
    "ohp_uneven_press": "좌우 비대칭",
    "ohp_incomplete_lockout": "락아웃 부족",
    "row_round_back": "등이 굽음",
    "row_too_upright": "상체 너무 세움",
    "row_body_english": "반동 사용",
    "incline_partial_rom": "가동범위 부족",
    "incline_uneven_press": "좌우 비대칭",
    "lat_excessive_lean": "상체 너무 젖힘",
    "lat_partial_rom": "가동범위 부족",
    "lat_uneven_pull": "좌우 비대칭",
    "lat_body_english": "반동 사용",
    "slr_too_high": "어깨선 초과",
    "slr_partial_rom": "수평 미도달",
    "slr_uneven": "좌우 비대칭",
    "slr_body_english": "반동 사용",
    "fly_too_open": "과도한 후방 신전",
    "fly_partial_rom": "수축 부족",
    "fly_uneven": "좌우 비대칭",
    "fly_body_english": "상체 흔들림",
    "sumo_round_back": "등 굽음",
    "sumo_partial_lockout": "락아웃 부족",
    "sumo_bar_drift": "바 경로 이탈",
    "sumo_hips_first": "엉덩이 먼저 올라감",
    "fr_too_high": "어깨선 초과",
    "fr_partial_rom": "수평 미도달",
    "fr_lean_back": "상체 뒤로 젖힘",
    "fr_body_english": "반동 사용",
    "cgbp_grip_too_wide": "그립 너무 넓음",
    "cgbp_partial_rom": "가동범위 부족",
    "cgbp_uneven_press": "좌우 비대칭",
    "cgbp_elbow_flare": "팔꿈치 벌어짐",
    "sc_upper_arm_drift": "상완 흔들림",
    "sc_partial_rom": "내림 부족",
    "sc_incomplete_lockout": "락아웃 부족",
    "crunch_too_high": "윗몸일으키기 형태",
    "crunch_partial_rom": "수축 부족",
    "crunch_lower_back_lift": "허리 들림",
    "legraise_lower_back_lift": "허리 들림",
    "legraise_partial_rom": "다리 미도달",
    "legraise_partial_descent": "끝까지 안 내림",
    "legraise_excessive_knee_flex": "무릎 굽힘 과도",
}

ERROR_BODY_PARTS = {
    "feet_spread": [27, 28],
    "caved_in_knees": [25, 26],
    "arms_spread": [15, 16],
    "arms_narrow": [15, 16],
    "excessive_arch": [23, 24],
    "spine_neutral": [11, 12, 23, 24],
    "lean_back": [11, 12, 23, 24],
    "loose_upper_arm": [13, 14],
    "weak_peak_contraction": [13, 14, 15, 16],
    "plank_high_back": [11, 12, 23, 24],
    "plank_low_back": [11, 12, 23, 24],
    "knee_over_toe": [25, 26, 27, 28],
    "ohp_uneven_press": [15, 16],
    "ohp_incomplete_lockout": [13, 14, 15, 16],
    "row_round_back": [11, 12, 23, 24],
    "row_too_upright": [11, 12, 23, 24],
    "row_body_english": [11, 12, 23, 24],
    "incline_partial_rom": [13, 14],
    "incline_uneven_press": [15, 16],
    "lat_excessive_lean": [11, 12, 23, 24],
    "lat_partial_rom": [15, 16],
    "lat_uneven_pull": [15, 16],
    "lat_body_english": [11, 12, 23, 24],
    "slr_too_high": [13, 14],
    "slr_partial_rom": [13, 14],
    "slr_uneven": [13, 14],
    "slr_body_english": [11, 12, 23, 24],
    "fly_too_open": [15, 16],
    "fly_partial_rom": [15, 16],
    "fly_uneven": [15, 16],
    "fly_body_english": [11, 12, 23, 24],
    "sumo_round_back": [0, 11, 12, 23, 24],
    "sumo_partial_lockout": [11, 12, 23, 24],
    "sumo_bar_drift": [15, 16, 11, 12],
    "sumo_hips_first": [11, 12, 23, 24],
    "fr_too_high": [13, 14, 15, 16],
    "fr_partial_rom": [13, 14, 15, 16],
    "fr_lean_back": [11, 12, 23, 24],
    "fr_body_english": [11, 12, 23, 24],
    "cgbp_grip_too_wide": [15, 16],
    "cgbp_partial_rom": [13, 14],
    "cgbp_uneven_press": [15, 16],
    "cgbp_elbow_flare": [13, 14],
    "sc_upper_arm_drift": [11, 12, 13, 14],
    "sc_partial_rom": [15, 16],
    "sc_incomplete_lockout": [13, 14, 15, 16],
    "crunch_too_high": [11, 12, 23, 24],
    "crunch_partial_rom": [11, 12],
    "crunch_lower_back_lift": [23, 24],
    "legraise_lower_back_lift": [23, 24],
    "legraise_partial_rom": [25, 26, 27, 28],
    "legraise_partial_descent": [25, 26, 27, 28],
    "legraise_excessive_knee_flex": [25, 26],
}

CATEGORY_HINTS = {
    "Stability": "발 가운데로 무게중심을 두고 좌우 흔들림을 줄여보세요.",
    "ROM": "rep 사이 깊이가 일정하지 않습니다. 매번 같은 깊이까지 컨트롤하면서 내려가세요.",
    "Movement Quality": "하강·상승 템포를 일정하게(예: 3초 내려가고 1초 올라오기) 유지하세요.",
    "Posture": "가슴을 천장 쪽으로 들고 시선을 정면 한 점에 고정해 척추 중립을 유지하세요.",
    "Core": "복압을 더 강하게 잡고 호흡 타이밍을 의식적으로 맞춰보세요.",
}
